- hosts: all
  become: yes
  tasks:
  - name: Chenking ping
    ping:
  - name: Update packages
    apt:
      name: apache2
      update_cache: yes
      state: present
  - name: restart apache2 server
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: install php module
    apt:
      name: "{{ item }}"
      state: present
    with_items:
     - php